version: '2'

services:
  insurgency:
    image: localhost:5000/timw/insurgency-server
    ports:
      - 27015:27015/udp
      - 27015:27015/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: hostname=mars
      io.rancher.container.pull_image: always
